server:
  port: ${mdsd.port.phfa}
spring:
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      file-size-threshold: 10MB # 文件大小门槛
      max-file-size: 10MB # 最大文件大小
      max-request-size: 11MB # 最大请求大小
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//${mdsd.ip.db}:1521/orcl?TraceLevel=ON
    hikari: # springboot 2.0 整合了hikari ,据说这是目前性能最好的java数据库连接池
      username: PHEP
      password: ENC(/odLmksGUGFhc587eZL8bucw61zLBjIpjC/RgziY6xk/CP48Ek9m6no3Xhe7rFim)
      minimum-idle: 3 # 最小空闲连接数量
      idle-timeout: 600000 # 空闲连接存活最大时间,默认600000（10分钟）
      maximum-pool-size: 10 # 连接池最大连接数,默认是10
      auto-commit: true # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 # 此属性控制池中连接的最长生命周期,值0表示无限生命周期,默认1800000即30分钟
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒,即30000
  redis:
    host: ${mdsd.ip.db}
    port: 6379
    database: 1
    password: ENC(/Qtj3m1yusm0G+DoTdTKnJqSpgwcJy3X7f1Sv6DCWz8MHRFaRM5JLXpn1CDfvU6M)
    jedis:
      pool:
        max-active: 16 # 连接池最大连接数,负值表示没有限制
        max-wait: 30s # 连接池最大阻塞等待时间,负值表示没有限制
        max-idle: 8 # 最大空闲连接数
        min-idle: 3 # 最小空闲连接数
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml # 扫描mapper包中的所有 .xml 文件
  configuration:
    cache-enabled: false
    jdbc-type-for-null: null # 配置JdbcTypeForNull, oracle数据库必须配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL日志
    map-underscore-to-camel-case: true # 开启驼峰功能,将下划线映射到驼峰大小写
# Swagger3 开关
springfox:
  documentation:
    swagger-ui:
      enabled: true
# 服务器环境IP&PORT配置
mdsd:
  ip:
    db: 192.168.0.126
    server: 192.168.0.96
    dasServer: 192.168.0.138
    im: https://192.168.0.119
  port:
    phfa: 20220
    auth: 8090
    das: 8097
    im: 48889