// 治疗
export default function GcCure() {
  return {
    registId: '',
    rsAdmissionTime: '',
    rsAdmissionDoctor: '',
    rsTaboo: '',
    rsRelativeTaboo: '',
    rsTalkStartTime: '',
    isRsInformed: '',
    isRsInformedArgee: '',
    rsInformedSignTime: '',
    rsTalkEndTime: '',
    sRsVein: '',
    rsRefuseReason: '',
    rsNihssBeforeId: '',
    firstPharmacyTime: '',
    bodyWeight: '',
    rsDrugs: '',
    rsAdaptation: '',
    rsDose: '',
    rsDoseRecommended: '',
    rsDoseActual: '',
    rsUrokinaseDose: '',
    isRsOtherDrug: '',
    rsOtherDrug: '',
    rsOthers: '',
    rsNihssAfterId: '',
    isRsAde: '',
    rsAdeTime: '',
    rsAdeType: '',
    rsAdeIhType: '',
    rsAdeIhSeverity: '',
    isRsAdeIahr: '',
    rsAdeOther: ''
  }
}
