export default function ExaminationReport() {
  return {
    daukNo: '',
    examNo: '',
    patientName: '',
    patientAge: '',
    patientGender: '',
    examClass: '',
    examSubClass: '',
    clinDiag: '',
    examMode: '',
    device: '',
    performedBy: '',
    applyTime: '',
    applyDept: '',
    applyPhysician: '',
    applyMemo: '',
    notice: '',
    examStartTime: '',
    examEndTime: '',
    reportTime: '',
    examPara: '',
    description: '',
    recommendation: '',
    conclusion: '',
    technician: '',
    reporter: '',
    resultStatus: '',
    verifiedBy: '',
    verifiedTime: ''
  }
}
