export default function GcDetection() {
  return {
    registId: '',
    bloodCollectionTime: '',
    diag: '',
    dispose: '',
    ecgDiagnosis: '',
    ecgException: '',
    ecgFile: '',
    ecgTime: '',
    firstNihssId: '',
    id: '',
    isEcg: '',
    isGcsFirst: '',
    isLvo: '',
    isNihssFirst: '',
    isSkullCt: '',
    skullCtTime: '',
    // 首次gcs评分id
    firstGcsId: '',
    isCt: '0',
    isCtAspects: '',
    // ct-aspects评分后循环id
    ctAspectsAfterId: '',
    // ct-aspects评分前循环id
    ctAspectsBeforeId: '',
    ctAspectsTime: '',
    ctEnterTime: '',
    ctLeaveTime: '',
    isMriAspects: '',
    // mri-aspects评分后循环id
    mriAspectsAfterId: '',
    // mri-aspects评分前循环id
    mriAspectsBeforeId: '',
    mriAspectsTime: '',
    mriStartTime: '',
    mriFinishTime: '',
    // 是否有实验室检查
    isLabInspection: '',
    // 是否有影像检查
    isScreenInspection: '',
    // 是否血常规
    isRbt: '',
    // 是否凝血常规
    isCf: '',
    // 是否肾功能及电解质
    isRef: '',
    // 是否CTA
    isCta: '',
    // 是否PWI
    isPwi: '',
    // 是否CTP
    isCtp: '',
    // 是否DWI
    isDwi: '',
    // 是否MRA
    isMra: '',
    // 是否MRI
    isMri: '',
    nihssFirstTime: '',
    gcsFirstTime: ''
  }
}
