export default function TriagePreview() {
  return {
    // 患者卡号信息表_主键ID(注: 新增操作时后端自处理)
    infoId: '',
    // 创建人
    createId: '',
    // 创建时间
    createTime: '',
    // 腕带编号
    tagNo: '',
    // 分诊护士
    nurseId: '',
    // 急诊编号
    regId: '',
    // 病历号
    patientId: '',
    // 三无患者
    isNoname: '',
    // 姓名
    name: '',
    // 性别
    gender: '',
    // 民族
    nation: '',
    // 联系电话
    tel: '',
    // 证件类型
    idcardType: '',
    // 证件号码
    identificationCard: '',
    // 出生日期
    birthday: '',
    // 年龄
    regAge: '',
    // 年龄补充
    regAgeCaption: '',
    // 分诊时间
    triageTime: '',
    // 职业
    job: '',
    // 住址
    address: '',
    // 备注
    describe: '',
    // 绿色通道
    channel: '',
    // 其他
    other: '',
    // 来院方式
    arriveType: '',
    // 患者主诉
    subjective: '',
    // 第二主诉
    secondSubjective: '',
    // 主诉判断依据主键编号
    knowledgeId: '',
    // "生、到、流
    datas: {
      // 生命体征
      vitalSigns: {
        // 是否有生命迹象(0:否,1：是)
        haslife: '',
        // 拒绝TPRBP(0:否,1：是)
        notprbp: '',
        // 体温
        temperature: '',
        // 脉搏(次/分钟)
        plus: '',
        // 呼吸(次/分钟)
        breath: '',
        // 舒张压(mmhg)
        dbp: '',
        // 收缩压(mmhg)
        sbp: '',
        // SPO₂ (%)
        spo: '',
        // 意识
        mind: '',
        // 采集时间
        acqTime: ''
      },
      // 到院信息
      arriveInfo: {
        // 到院时间
        arriveTime: '',
        // 发病时间
        diseaseTime: '',
        // 120接诊时间
        acceptTime: '',
        // 120接诊地址
        acceptAddress: '',
        // 发病地址
        address: '',
        // 陪送/110/120/相关人员地址
        arrivewithAddress: '',
        // 陪送/110/120/相关人员姓名
        arrivewithName: '',
        // 陪送/110/120/相关人员电话
        arrivewithTel: ''
      },
      // 流行病学史
      infectHistory: {
        // 死亡或者动物接触史
        diseaseTouch: '',
        // 疫区旅游史
        epidemicArea: '',
        // 流行病病史
        infectMsg: '',
        // 入院前三天有发热学史
        isHvaeFeverHistory: '',
        // 24小时体温超过38度
        isFever: '',
        // 发热时间
        feverTime: ''
      }
    },
    // 患者评分
    scores: [],
    // 分级
    grade: {
      // 系统分级
      syslevel: '',
      // 护士分诊的级别
      resetLevel: ''
    },
    // 患者去向
    whereabouts: {
      // 就诊科室
      departmentId: '',
      // 就诊医生
      checkDoctorId: '',
      // 去向
      turnResult: ''
    }
  }
}
