// 字典名映射
const dicConstant = {
  // 证件类型
  idCardType: 'STROKE_IDCARDTYPE',
  // 分诊-意识
  triageMind: 'consciousness',
  // 分诊-绿色通道
  greenChannel: 'greenChannel',
  // 分诊-就诊科室
  department: 'departmentId',
  // 分诊-就诊医生
  doctor: 'STROKE_DOCTOR',
  // 预览-急救-疾病类别
  diseaseCategory: 'diseaseCategory',
  // 预览-急救-意识
  phepConsciousness: 'PHEP_consciousness',
  // 预览-急救-病史提供者
  medicalHisProType: 'medicalHisProType',
  // 预览-急救-过敏史
  allergicHistory: 'allergicHistory',
  // 来院方式
  comingType: 'STROKE_COMING_TYPE',
  // 来院方式简称
  comingTypeShort: 'STROKE_COMING_TYPE_SHORT',
  // 院前急救-初步印象
  impression: 'STROKE_IMPRESSION',
  // 院前急救-专家评估
  evaluate: 'STROKE_FAST',
  // 预览-急救-性别
  gender: 'STROKE_GENDER',
  // 民族
  strokeNation: 'STROKE_NATION',
  // 紧急联系人与患者关系
  urgentType: 'STROKE_URGENT_TYPE',
  // 病情分级code
  illnessLevel: 'STROKE_ILLNESS_LEVEL',
  // 意识code
  mind: 'STROKE_MIND',
  // 陈述者与患者关系code
  declarantType: 'STROKE_DECLARANT_TYPE',
  // 用药史code
  pharmacyHistory: 'STROKE_PHARMACY_HISTORY',
  // 抗血小板药物
  phAntiplatelet: 'STROKE_PH_ANTIPLATELET',
  // 抗凝药物
  phAnticoagulation: 'STROKE_PH_ANTICOAGULATION',
  // 实验室检查类型
  lisItemType: 'STROKE_LIS_ITEM_TYPE',
  // 影像学检查类型
  imageItemType: 'STROKE_IMAGE_ITEM_TYPE',
  // 初步诊断
  diag: 'STROKE_DIAG',
  // 初步处置
  dispose: 'STROKE_DISPOSE',
  // 症状
  symptom: 'STROKE_SYMPTOM',
  // 既往病史
  pastHistory: 'STROKE_PAST_HISTORY',
  // 心电图异常
  electrocardiogram: 'STROKE_ECG_EXCEPTION',
  // 患者来源
  comeType: 'STROKE_COME_TYPE',
  // 溶栓禁忌
  rsTaboo: 'STROKE_RS_TABOO',
  rsRelativeTaboo: 'STROKE_RS_RELATIVE_TABOO',
  rsRefuseReason: 'STROKE_RS_REFUSE_REASON',
  rsAdaptation1: 'STROKE_RS_ADAPTATION1',
  rsAdaptation2: 'STROKE_RS_ADAPTATION2',
  rsDose: 'STROKE_RS_DOSE',
  rsOtherDrug: 'STROKE_RS_OTHER_DRUG',
  rsAdeType: 'STROKE_RS_ADE_TYPE',
  rsAdeOther: 'STROKE_RS_ADE_OTHER',
  rsAdeIhType: 'STROKE_RS_ADE_IH_TYPE',
  rsAdeIhSeverity: 'STROKE_RS_ADE_IH_SEVERITY',
  pciTaboo: 'STROKE_PCI_TABOO',
  pciRefuseReason: 'STROKE_PCI_REFUSE_REASON',
  pciAdaptation: 'STROKE_PCI_ADAPTATION',
  ticiLevel: 'STROKE_TICI_LEVEL',
  pciStrategy: 'STROKE_PCI_STRATEGY',
  pciAdeType: 'STROKE_PCI_ADE_TYPE',
  delayReason: 'STROKE_DELAY_REASON',
  whereabouts: 'STROKE_WHEREABOUTS',
  admissionDept: 'STROKE_ADMISSION_DEPT',
  gcsResult: 'STROKE_GCS_RESULT',
  nihssResult: 'STROKE_NIHSS_RESULT',
  qrCode: 'STROKE_QRCODE',
  reportStatus: 'STORKE_REPORT_STATUS',
  // 病情判断
  conditionGrade: 'conditionGrade',
  // 病情转归
  rescueChangeResult: 'rescueChangeResult',
  // Tnt单位
  tntUnit: 'PHFA_0020'
}
export default dicConstant
