// 字典code
export const dicConstant = {
  // 性别
  genderCode: 'genderDict',
  // 诊断
  diagnosisCode: 'diagnosisDict',
  // 来院方式
  comingCode: 'comingDict',
  // 来院方式(简称)
  comingCodeSHORTCode: 'comingCodeShortDict',
  // 病情评估
  distressCaseCode: 'distressCaseDict',
  // 发病区间
  attackZoneCode: 'attackZoneDict',
  // 是否
  yesOrNoCode: 'yesOrNoDict',
  // 远程传输心电图方式
  remoteEcgtranWayCode: 'remoteEcgtranWayDict',
  // 意识
  senseCode: 'senseDict',
  // 转院类型
  transferTypeCode: 'transferTypeDict',
  // 出车单位
  ambulanceDepartmentCode: 'ambulanceDepartmentDict',
  // 抗血小板药物
  drugItemsCode: 'drugItemsDict',
  // 溶栓筛查
  thrombolyticScreeningCode: 'thrombolyticScreeningDict',
  // 院前溶栓场所
  faThrombolyticPlaceCode: 'faThrombolyticPlaceDict',
  // 溶栓药物
  thrombolyticDrugTypeCode: 'thrombolyticDrugTypeDict',
  // 溶栓剂量
  thrombolyticDrugCode: 'thrombolyticDrugDict',
  // 手术场所
  pciPlaceCode: 'pciPlaceDict',
  // 会诊类型
  consultationTypeCode: 'consultationTypeDict',
  // 夹层类型
  interlayerTypeCode: 'interlayerTypeDict',
  // 治疗策略
  treatmentStrategyCode: 'treatmentStrategyDict',
  // 危险分层
  highriskLaminationCode: 'highriskLaminationDict',
  // Killip分级
  killipLevelCode: 'killipLevelDict',
  // 非ACS心源性胸痛类型
  nacsTypeCode: 'nacsTypeDict',
  // 其它非心源性胸痛类型
  nccpTypeCode: 'nccpTypeDict',
  // 处理措施
  handleWayCode: 'handleWayDict',
  // 实验室检查类型
  diagnosisTestTypeCode: 'diagnosisTestTypeDict',
  // Myo单位
  myoUnitCode: 'myoUnitDict',
  // CKMB单位
  ckmbUnitCode: 'ckmbUnitDict',
  // Ddimer单位
  ddimerUnitCode: 'ddimerUnitDict',
  // 再次危险分层
  graceRehazardLevelCode: 'graceRehazardLevelDict',
  // 影像学检查
  pacsTypeCode: 'pacsTypeDict',
  // 血流TIMI分级
  timiLevelCode: 'timiLevelDict',
  // 无再灌注措施原因
  perfusionMeasureCode: 'perfusionMeasureDict',
  // 再灌注策略
  reperfusionMeasureCode: 'reperfusionMeasureDict',
  // 院内溶栓场所
  ihThrombolyticPlaceCode: 'ihThrombolyticPlaceDict',
  // 溶栓后措施
  reperfusionMeasureRsCode: 'reperfusionMeasureRsDict',
  // 转运PCI
  pciTransferTypeCode: 'pciTransferTypeDict',
  // 入路位置
  routeCode: 'routeDict',
  // 冠脉造影
  cagPositionCode: 'cagPositionDict',
  // 术中处理
  pciHandleWayCode: 'pciHandleWayDict',
  // 植入支架个数
  bracketNumCode: 'bracketNumDict',
  // 支架种类
  bracketTypeCode: 'bracketTypeDict',
  // 腔内影像
  intracavityImageCode: 'intracavityImageDict',
  // 功能检测
  functionTestCode: 'functionTestDict',
  // 抗凝药物
  anticoagulationDrugCode: 'anticoagulationDrugDict',
  // 延误原因
  delayReasonCode: 'delayReasonDict',
  // 狭窄程度
  narrowLevelCode: 'narrowLevelDict',
  // 抗凝单位
  anticoagulationUnitCode: 'anticoagulationUnitDict',
  // 民族
  nationalityCode: 'nationalityDict',
  // 文化程度
  cultureDegreeCode: 'cultureDegreeDict',
  // 证件类型
  idCardCode: 'idCardDict',
  // 婚姻状况
  maritalCode: 'maritalDict',
  // 职业
  jobCode: 'jobDict',
  // 病情评估明星
  distressCaseDetailCode: 'distressCaseDetailDict',
  // 医保类型
  insuranceCode: 'insuranceDict',
  // 术中并发症
  pciComplicationCode: 'pciComplicationDict'
}

export const timeFormat = {
  birthday: 'yyyy-MM-dd',
  default: 'yyyy-MM-dd HH:mm'
}
