export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
export const SET_JWT_TOKEN = 'SET_JWT_TOKEN'
export const SET_DICTIONARY = 'SET_DICTIONARY'// 字典
export const SET_LOGIN_USER_INFO = 'SET_LOGIN_USER_INFO'// 登录用户信息
export const SET_HOSPITAL_LIST = 'SET_HOSPITAL_LIST'// 医院列表
export const SET_HOSPITAL_ID = 'SET_HOSPITAL_ID'// 医院ID
export const SET_HOSPITAL_AREA_LIST = 'SET_HOSPITAL_AREA_LIST'// 院区列表
export const SET_HOSPITAL_AREA = 'SET_HOSPITAL_AREA'// 院区
export const SET_REGIST_ID = 'SET_REGIST_ID'// 病历ID
export const SET_READ_ONLY = 'SET_READ_ONLY'// 是否只读
export const SET_RECEIVE_DEPT = 'SET_RECEIVE_DEPT'// 接诊科室
export const SET_LEAVE_LOCATION_TIME = 'SET_LEAVE_LOCATION_TIME'// 离开现场时间
export const SET_PATIENT_NAME = 'SET_PATIENT_NAME'// 患者姓名
export const SET_EM_ID = 'SET_EM_ID'
export const SET_VISIT_TYPE = 'SET_VISIT_TYPE'// 来院方式
export const SET_IS_PICK_READ = 'SET_IS_PICK_READ'// 调阅
export const SET_DIAGNOSIS = 'SET_DIAGNOSIS'// 病情判断
export const SET_ARRIVAL_TIME = 'SET_ARRIVAL_TIME'// 到达急诊或门诊时间
export const SET_ADMITTING_DIAGNOSIS = 'SET_ADMITTING_DIAGNOSIS'// 入院诊断
export const SET_ATTACK_TIME = 'SET_ATTACK_TIME'// 发病时间
export const SET_ARRIVE_HOSPITAL_TIME = 'SET_ARRIVE_HOSPITAL_TIME'// 到院时间
export const SET_ARRIVE_HOSPITAL_CONNECT = 'SET_ARRIVE_HOSPITAL_CONNECT'// 到院交接
export const SET_BINDING = 'SET_BINDING'// 绑定
export const SET_PHFA_DEATH = 'SET_PHFA_DEATH'// 院前急救死亡
export const SET_PHFA_DEATH_TIME = 'SET_PHFA_DEATH_TIME'// 院前急救死亡时间
export const SET_PIAT_DEATH = 'SET_PIAT_DEATH'// 预检分诊死亡