// 字典code
const dicConstant = {
  // 证件类型
  idCardType: 'STROKE_IDCARDTYPE',
  // 分诊-意识
  triageMindCode: 'consciousness',
  // 分诊-绿色通道
  greenChannelCode: 'greenChannel',
  // 分诊-就诊科室
  departmentCode: 'departmentId',
  // 分诊-就诊医生
  doctorCode: 'STROKE_DOCTOR',
  // 预览-急救-疾病类别
  diseaseCategoryCode: 'diseaseCategory',
  // 预览-急救-意识
  phepConsciousnessCode: 'PHEP_consciousness',
  // 预览-急救-病史提供者
  medicalHisProTypeCode: 'medicalHisProType',
  // 预览-急救-过敏史
  allergicHistoryCode: 'allergicHistory',
  // 来院方式
  comingTypeCode: 'STROKE_COMING_TYPE',
  // 来院方式简称
  comingTypeShortCode: 'STROKE_COMING_TYPE_SHORT',
  // 院前急救-初步印象
  impressionCode: 'STROKE_IMPRESSION',
  // 院前急救-专家评估
  evaluate: 'STROKE_FAST',
  // 预览-急救-性别
  genderCode: 'STROKE_GENDER',
  // 民族
  strokeNationCode: 'STROKE_NATION',
  // 紧急联系人与患者关系
  urgentTypeCode: 'STROKE_URGENT_TYPE',
  // 病情分级code
  illnessLevelCode: 'STROKE_ILLNESS_LEVEL',
  // 意识code
  mindCode: 'STROKE_MIND',
  // 陈述者与患者关系code
  declarantTypeCode: 'STROKE_DECLARANT_TYPE',
  // 用药史code
  pharmacyHistoryCode: 'STROKE_PHARMACY_HISTORY',
  // 抗血小板药物
  phAntiplateletCode: 'STROKE_PH_ANTIPLATELET',
  // 抗凝药物
  phAnticoagulationCode: 'STROKE_PH_ANTICOAGULATION',
  // 实验室检查类型
  lisItemTypeCode: 'STROKE_LIS_ITEM_TYPE',
  // 影像学检查类型
  imageItemTypeCode: 'STROKE_IMAGE_ITEM_TYPE',
  // 初步诊断
  diagCode: 'STROKE_DIAG',
  // 初步处置
  disposeCode: 'STROKE_DISPOSE',
  // 症状
  symptomCode: 'STROKE_SYMPTOM',
  // 既往病史
  pastHistoryCode: 'STROKE_PAST_HISTORY',
  // 心电图异常
  electrocardiogramCode: 'STROKE_ECG_EXCEPTION',
  // 患者来源
  comeType: 'STROKE_COME_TYPE',
  // 溶栓禁忌
  rsTaboo: 'STROKE_RS_TABOO',
  rsRelativeTaboo: 'STROKE_RS_RELATIVE_TABOO',
  rsRefuseReason: 'STROKE_RS_REFUSE_REASON',
  rsAdaptation1: 'STROKE_RS_ADAPTATION1',
  rsAdaptation2: 'STROKE_RS_ADAPTATION2',
  rsDose: 'STROKE_RS_DOSE',
  rsOtherDrug: 'STROKE_RS_OTHER_DRUG',
  rsAdeType: 'STROKE_RS_ADE_TYPE',
  rsAdeOther: 'STROKE_RS_ADE_OTHER',
  rsAdeIhType: 'STROKE_RS_ADE_IH_TYPE',
  rsAdeIhSeverity: 'STROKE_RS_ADE_IH_SEVERITY',
  pciTaboo: 'STROKE_PCI_TABOO',
  // 介入治疗拒绝原因
  pciRefuseReason: 'STROKE_PCI_REFUSE_REASON',
  pciAdaptation: 'STROKE_PCI_ADAPTATION',
  ticiLevel: 'STROKE_TICI_LEVEL',
  pciStrategy: 'STROKE_PCI_STRATEGY',
  // 介入不良事件类型
  pciAdeType: 'STROKE_PCI_ADE_TYPE',
  delayReason: 'STROKE_DELAY_REASON',
  whereabouts: 'STROKE_WHEREABOUTS',
  admissionDept: 'STROKE_ADMISSION_DEPT',
  gcsResult: 'STROKE_GCS_RESULT',
  nihssResult: 'STROKE_NIHSS_RESULT',
  // 病情判断
  conditionGrade: 'conditionGrade',
  // 病情转归
  rescueChangeResult: 'rescueChangeResult',
  // Tnt单位
  tntUnit: 'PHFA_0020'
}
export default dicConstant
